'\" t
.\"     Title: cjxy
.\"    Author: Jan Schnasse
.\" Generator: Asciidoctor 1.5.5
.\"      Date: 2020-04-10
.\"    Manual: CJXY
.\"    Source: CJXY
.\"  Language: English
.\"
.TH "CJXY" "1" "2020-04-10" "CJXY" "CJXY"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.LINKSTYLE blue R < >
.SH "NAME"
cjxy \- converts csv,jason,xml,yaml, and rdf to each other
.SH "SYNOPSIS"
.sp
\fBcjxy\fP [\-hV] [\-f=JsonLdFrame] [\-t=<type>] <inputFile>
.SH "OPTIONS"
.sp
\fB<inputFile>\fP
.RS 4
Input file.
.RE
.sp
\fB\-o, \-\-out\-file\fP=\fIOUT_FILE\fP
.RS 4
Write result to file \fIOUT_FILE\fP.
.RE
.sp
\fB\-c, \-\-capture\fP
.RS 4
Capture specimen if it\(cqs a picture of a life form.
.RE
.sp
\fB\-f, \-\-frame\fP=\fIJsonLdFrame\fP
.RS 4
A json\-ld frame as json \fIJsonLdFrame\fP
.RE
.sp
\fB\-h, \-\-help\fP
.RS 4
Show this help message and exit.
.RE
.sp
\fB\-t, \-\-type\fP=\fITYPE\fP
.RS 4
\fITYPE\fP muts be one of yaml,json,xml,rdf
.RE
.sp
\fB\-V, \-\-version\fP
.RS 4
Print version information and exit.
.RE
.SH "EXIT STATUS"
.sp
\fB0\fP
.RS 4
Success.
.RE
.sp
\fB1\fP
.RS 4
Failure.
.RE
.SH "RESOURCES"
.sp
\fBProject web site:\fP \c
.URL "https://github.com/jschnasse/cjxy" "" ""
.SH "COPYING"
.sp
Copyright \(co 2020 Jan Schnasse.
\&.br
Free use of this software is granted under the terms of the EPL License.
.SH "AUTHOR(S)"
.sp
\fBJan Schnasse\fP
.RS 4
Author(s).
.RE