#! /bin/bash


function download(){
 (
 git clone https://github.com/jschnasse/oi /tmp/oi
 cd /tmp/oi
 )
}

# Install with
function install(){
 (
 mvn package
 sudo cp src/main/resources/oi /usr/bin
 sudo cp target/oi.jar /usr/lib
 cd man
 asciidoctor -b manpage man.adoc
 sudo cp oi.1 /usr/share/man/man1/
 sudo mandb
 )
}
if [ -f /usr/lib/libprocname.so ]
then
    LD_PRELOAD=/usr/lib/libprocname.so PROCNAME=oi java -jar /usr/lib/oi.jar $@
else
    java -jar /usr/lib/oi.jar $@
fi
