FROM adoptopenjdk/openjdk12:latest as build
RUN jlink \
    --add-modules java.base,java.naming,java.xml,jdk.crypto.ec \
    --verbose \
    --strip-debug \
    --compress=1 \
    --no-header-files \
    --no-man-pages \
    --output /opt/jvm_for_oi
    
FROM panga/alpine:3.8-glibc2.27

LABEL maintainer="Jan Schnasse"

COPY --from=build /opt/jvm_for_oi /usr/share/jvm_for_oi

COPY target/oi.jar /usr/lib
COPY src/main/resources/oi /usr/bin
RUN ln -s /usr/share/jvm_for_oi/bin/java /usr/bin/jvm_for_oi \
&& chmod +x /usr/bin/oi 

RUN jvm_for_oi -jar /usr/lib/oi.jar /etc/passwd -d":" --header="login,password,uid,gid,comment,home,shell" -icsv
