= oi(1)
Jan Schnasse
v0.4.2
:doctype: manpage
:manmanual: OI
:mansource: OI
:man-linkstyle: pass:[blue R < >]

== Name

oi - converts csv,jason,xml,yaml, and rdf to each other

== Synopsis

*oi* [-hvV] [-vv] [-d=Delimiter] [-f=JsonLdFrame]
            [--header=HeaderFields] [-i=<inputType>] [-q=QuoteChar] [-t=<type>]
            [<inputFile>]
	    
== Options

*[<inputFile>]*::
  Input file.
  
*-d, --delimiter*::
  delimiter for csv
  
*-f, --frame*=_JsonLdFrame_::   
  A json-ld frame as json _JsonLdFrame_
   
*-h, --help*::
  Show this help message and exit.
  
*--header*::  
  A comma separated list of headers. Use this option to specify
  headers for CSV files.

*-i, --inputType**::
  oi tries to recognize the input type based on file extensions. Use this
  option to explicitly provide an input type: yml,json,xml,rdf,context,csv.
*-q, --quoteChar**::
  use the specified char when parsing strings in csv files.
  
*-t, --type*=_TYPE_::
  _TYPE_ must be one of yaml,json,xml,rdf,context
  
*-V, --version*::
  Print version information and exit.

== Exit status

*0*::
  Success.


*1*::
  Failure.


== Resources

*Project web site:* https://github.com/jschnasse/oi

== Copying

Copyright (C) 2020 {author}. +
Free use of this software is granted under the terms of the EPL License.