'\" t
.\"     Title: oi
.\"    Author: Jan Schnasse
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2020-12-17
.\"    Manual: OI
.\"    Source: OI
.\"  Language: English
.\"
.TH "OI" "1" "2020-12-17" "OI" "OI"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
oi \- converts csv,jason,xml,yaml, and rdf to each other
.SH "SYNOPSIS"
.sp
\fBoi\fP [\-hvV] [\-vv] [\-d=Delimiter] [\-f=JsonLdFrame]
[\-\-header=HeaderFields] [\-i=<inputType>] [\-q=QuoteChar] [\-t=<type>]
[<inputFile>]
.SH "OPTIONS"
.sp
\fB[<inputFile>]\fP
.RS 4
Input file.
.RE
.sp
\fB\-d, \-\-delimiter\fP
.RS 4
delimiter for csv
.RE
.sp
\fB\-f, \-\-frame\fP=\fIJsonLdFrame\fP
.RS 4
A json\-ld frame as json \fIJsonLdFrame\fP
.RE
.sp
\fB\-h, \-\-help\fP
.RS 4
Show this help message and exit.
.RE
.sp
\fB\-\-header\fP
.RS 4
A comma separated list of headers. Use this option to specify
headers for CSV files.
.RE
.sp
\fB\-i, \-\-inputType\fP*
.RS 4
oi tries to recognize the input type based on file extensions. Use this
option to explicitly provide an input type: yml,json,xml,rdf,context,csv.
.RE
.sp
\fB\-q, \-\-quoteChar\fP*
.RS 4
use the specified char when parsing strings in csv files.
.RE
.sp
\fB\-t, \-\-type\fP=\fITYPE\fP
.RS 4
\fITYPE\fP must be one of yaml,json,xml,rdf,context
.RE
.sp
\fB\-V, \-\-version\fP
.RS 4
Print version information and exit.
.RE
.SH "EXIT STATUS"
.sp
\fB0\fP
.RS 4
Success.
.RE
.sp
\fB1\fP
.RS 4
Failure.
.RE
.SH "RESOURCES"
.sp
\fBProject web site:\fP \c
.URL "https://github.com/jschnasse/oi" "" ""
.SH "COPYING"
.sp
Copyright \(co 2020 Jan Schnasse.
.br
Free use of this software is granted under the terms of the EPL License.
.SH "AUTHOR"
.sp
Jan Schnasse